### ISSUE TITLE
Email notification failed: failed to send using smtp: timed out

### ISSUE THREAD

**Issue by nbraun1** [offen/docker-volume-backup#304] opened 2023-11-18 18:42 UTC
**Describe the bug**
I have configured the environment variable `NOTIFICATION_URLS` so that an e-mail notification is possible in the event of a failed backup:

`smtp://mail%40domain.com:ls3wer%263%23%21dksa45@smtp.office365.com:587/?from=mail%40domain.com&to=mail%40domain.com&fromname=backup&title=Backup`

But I get an error message:

`An error occurred calling the registered hooks: runHooks: error running hook: notify: error notifying: sendNotification: error sending message: failed to send using smtp: timed out`

I also played around with shoutrrr's query parameters like `Auth` and `Encryption` as described [here](https://containrrr.dev/shoutrrr/v0.8/services/email/).

**Version (please complete the following information):**
 - Image Version: v2.33.2
 - Docker Version: 24.0.7
 - Docker Compose Version (if applicable): v2.21.0

**EDIT:** I have tried the same url without url encoding, but the error is always the same.

**Comment by m90** [comment] 2023-11-18 18:58
This is a duplicate of https://github.com/offen/docker-volume-backup/issues/216

Unfortunately there is nothing around this isse that can be fixed in this tool, as your server does what is said in the error message: it times out. Maybe you can look for issues around the internet that describe the same phenomenon when connecting to Office 365 SMTP servers?

**Closed by m90** 2023-11-18 18:58 UTC
