### ISSUE TITLE
tar is closed before gzip writer

### ISSUE THREAD

**Issue by michalmiddleton** [offen/docker-volume-backup#183] opened 2023-01-21 21:33 UTC
**Describe the bug**
Hi, while poking around and testing zstd compression instead of gzip, I think I discovered a logical error in the code. 
It's quite possible this issue never surfaced when using gzip. 

Issue: 
When closing file, tar and gzip writers, tar writer gets closed before gzip writer: https://github.com/offen/docker-volume-backup/blob/1e36bd3eb7148df6f60db7486d4750a14c032230/cmd/backup/archive.go#L75 
Imo, the order of closing should be gzip -> tar -> file. 

I noticed it when troubleshooting one zst archive that had a corrupted block at the end.

**Comment by m90** [comment] 2023-01-22 08:25
I'm not entirely sure about your reasoning. For how I understand it, the `tarWriter` would need to be closed first, else the code would risk that the `tarWriter` tries to write to the already closed `gzipWriter`.

Or, to spell it out: `tarWriter` writes to `gzipWriter` writes to `file`, which means they will be closed in that exact order.

---

I also tried applying your suggestion here: https://github.com/offen/docker-volume-backup/commit/82456e3e7713584324db88789bd8920fb07edd7d but this makes all tests fail with the following error at runtime:

```
error creating archive: compress: error closing tar writer: flate: closed writer
```

Maybe the issue you ran into when trying to use `zstd` was caused by something else?

**Closed by m90** 2023-01-22 08:25 UTC
