### ISSUE TITLE
Ability to create multiple backup.tar.gz based on the input array of directories

### ISSUE THREAD

**Issue by larskruckow** [offen/docker-volume-backup#29] opened 2021-10-23 16:47 UTC
As far as I can tel, it works by taking everything in `/backup/*` and adding that to a single tar.gz file.
My use case is as follows:
I run this in docker-compose separately from the running containers.
All my containers data dirs are located in lets say: `/docker-volumes/app1` `/docker-volumes/app2` etc.
I have grouped them by schedule for backups, eg. nightly, weekly etc. and have an instance of docker-volume-backup running per schedule, mapping the relevant volumes to them.
I've gotten the label feature to work brilliantly stopping all the "nightly" ones at night, backing them up, then starting them back up.
I can't seem to figure out an easy way to have this do the backups "one by one".
What I would like to see is an option to have every dir in `/backup/*` be treated as a single backup so that I could have 
App1, App2, App3 in separate tar.gz files instead of a single tar.gz with App1, App2, App3 inside.
Is the only alternative to run multiple of these containers?

Thanks for a great little container!

**Comment by m90** [comment] 2021-12-05 09:12
After moving this around in the back of my head for a little longer, I think this is how it could work:

- consumers can mount an arbitrary number of configuration files into the container's `/etc/backup.d` directory (e.g. `/etc/backup.d/10app.env` and `/etc/backup.d/20database.env`)
- the entrypoint script checks whether that directory exists
- in case yes, it creates a crontab entry for each of the files and tells the `backup` binary to read configuration values from the file in addition to the defined environment variables
- in case no, a cron will be created from environment variables (i.e. the current behavior)

Open questions:
- this means that when configuration files change, the container will need to be restarted. Is that common practice or possibly unexpected behavior?

**Comment by rpatel3001** [comment] 2022-02-24 01:50
Something like https://github.com/fsnotify/fsnotify could trigger a config reload.

**Comment by m90** [comment] 2022-03-04 13:06
This is now possible as of `v2.14.0`. While I already had it working I did not implement `inotify` for file changes as it would require adding the `openrc` package to the container, adding slightly more than 2MB to the image size. In case this turns out to be a problem / requested feature for users, it can always be added in a later step.

**Closed by m90** 2022-03-04 13:06 UTC
Labels: enhancement
